import SwaggerAutogen from "swagger-autogen";
import { SwaggerOptions } from "swagger-ui-express";
import "dotenv/config";
import { pjProfile } from "../__tests__/mocks/profile.mock";
import { ProfileType } from "../entities/Profile.entity";

const swaggerAutogen = SwaggerAutogen();

const doc: SwaggerOptions = {
  info: {
    version: "1.0.0",
    title: "WeFit API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `localhost:${process.env.PORT || 4568}`,
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Profile",
      description: "The profile creator API",
    },
  ],
  definitions: {
    ProfileInput: {
      $profileType: "pj/pf",
      $email: "renanpj@gmail.com",
      $name: "Renan PJ",
      $cellphone: "+5511973965919",
      $phoneNumber: "+5511973965919",
      $cpf: "888.348.307-33",
      cnpj: "86.682.527/0001-69",
      $address: {
        $cep: "09821-540",
        $publicPlace: "Av. Ivanovsky",
        $number: 273,
        $city: "São Bernardo do Campo",
        complement: "",
        $neighborhood: "Botujuru",
        $state: "São Paulo",
      },
    },
    Profile: {
      $id: "2b3a6481-db77-4d9b-904d-df0d80a9a615",
      $profileType: "pj",
      $email: "renanpj@gmail.com",
      $name: "Renan PJ",
      $cellphone: "+5511973965919",
      $phoneNumber: "+5511973965919",
      $cpf: "888.348.307-33",
      cnpj: "86.682.527/0001-69",
      $createdAt: "2024-02-03T21:34:52.581Z",
      $address: {
        $id: "2b3a6481-db77-4d9b-904d-df0d80a9a615",
        $cep: "09821-540",
        $publicPlace: "Av. Ivanovsky",
        $number: 273,
        $city: "São Bernardo do Campo",
        $neighborhood: "Botujuru",
        $state: "São Paulo",
      },
    },
  },
};

const outputFile = "./swagger_output.json";
const endpointsFiles = ["../routes/index.ts"];

swaggerAutogen(outputFile, endpointsFiles, doc);
